name: Test and deploys releases

on:
  workflow_run:
    workflows: ['unit_testing']
      push:
        tags: 'v*'
      types:
        - completed

jobs:
  release:
    name: "Tagged Release"
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - name: Create Github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "v${{ env.VERSION }}"
          files: |
            LICENSE
            dist/intrusion*

  pypi:
    name: Deploy to PyPI
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get version from versioneer
        run: |
          VER=$(echo $(python -c "import versioneer; print(versioneer.get_versions()['version'].replace('+', '-'))"))
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Install pypa/build and build a binary wheel and a source tarball
        run: |
          python -m pip install --upgrade pip
          python -m pip install build --user
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  docker:
    name: Deploy to Docker Hub (latest)
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get version from versioneer
        run: |
          VER=$(echo $(python -c "import versioneer; print(versioneer.get_versions()['version'].replace('+', '-'))"))
          echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
          no-cache: true
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            afonsoc12/intrusion-monitor:latest
            afonsoc12/intrusion-monitor:v${{ env.VERSION }}
            ghcr.io/afonsoc12/intrusion-monitor:latest
            ghcr.io/afonsoc12/intrusion-monitor:v${{ env.VERSION }}

  dummy:
    name: Dummy step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
