name: Run unit tests

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: Runs pytest unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest requests-mock
      - name: Run pytest
        run: pytest test/*