name: Update Docker Hub description and README

on:
  push:
    paths:
      - README.md   # Changes on README.md updates Docker Hub description and README 

jobs:
            
  docker-description:
    name: Update Docker Hub description and README
    if: ${{ github.ref == 'refs/heads/main' && startsWith( github.ref, refs/tags/v ) }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Docker Hub description and README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          short-description: ./README.md
          readme-filepath: ${{ github.event.repository.description }}
          repository: afonsoc12/intrusion-monitor
